### ISSUE TITLE
Refined Storage quest references mod not present: Immersive Engineering

### ISSUE THREAD

**Issue by risric** [ClaudiusMinimus/Create_Potato#3]
The first Refined Storage quest description states: "Make sure you have some power. You will want to have started Immersive Engineering." However, Immersive Engineering is not present in the pack. Should this reference the Alternator from 'Create Crafts and Additions'? (ASIDE: The Alternator is the only other source of other source of RF/FE I've identified.)

**Comment by ClaudiusMinimus** [comment]
Thank you for reporting this. Just fixed it and will be in the next release.
